"""The 1997 Županijski dom election, transcribed from the DIP report.

Source: `files/rezultati_sabor_2024/1997/1997_3_Rezultati_Sabor_zupanijski_dom.pdf`
— "Izvješće o konačnim službenim rezultatima izbora zastupnika u Županijski dom
Sabora Republike Hrvatske", Klasa 013/01/97-01/01, Zagreb, 23 April 1997.

That PDF is a **pure scan**: 43 pages, each a single CCITT Group 4 image with no
text layer, so nothing could be parsed out of it. The pages were rendered with
`tools/extract_scanned_pdf.py` and transcribed by hand, which is why the data
lives here as a literal rather than being read from the file at import time.

`code` is the county's own 2-char code, which the document's numbering happens
to match exactly (01 Zagrebačka … 21 Grad Zagreb). Checked on every county:
the list votes sum to `valid_total`, `valid_total + invalid == voted`, and each
county returns its 3 seats with 3 named members — 63 in all.

Cross-checked against the party totals published for this election: all 21
coalitions match to the vote, and the whole file sums to 2,529,412 valid of
2,615,474 cast with 86,062 invalid — the published figures exactly.

One silent correction: the report misspells the Istrian SDP list's partner as
"Hrvatska **nardona** stranka - HNS". Transcribed faithfully it left that
county's 13,576 votes out of the national SDP-HNS total; normalised, the total
lands on 281,496 exactly. It is DIP's typo, not the transcription's.
"""

COUNTIES = [{'code': '01',
  'name': 'Zagrebačka županija',
  'registered': 234405,
  'voted': 173595,
  'invalid': 4694,
  'valid_total': 168901,
  'lists': [{'n': 1,
             'parties': ['Hrvatska čista stranka prava - HČSP'],
             'holder': 'Ivan Gabelica, dipl. iur.',
             'votes': 3243,
             'pct': 1.92},
            {'n': 2,
             'parties': ['Hrvatska demokratska zajednica - HDZ'],
             'holder': 'Dr. Franjo Tuđman',
             'votes': 78018,
             'pct': 46.19},
            {'n': 3,
             'parties': ['Hrvatska građansko seljačka stranka - HGSS',
                         'Hrvatski nezavisni demokrati - HND'],
             'holder': 'Josip Manolić',
             'votes': 3238,
             'pct': 1.92},
            {'n': 4,
             'parties': ['Hrvatska seljačka stranka - HSS',
                         'Hrvatska socijalno liberalna stranka - HSLS'],
             'holder': 'Zlatko Tomčić, dipl. ing.',
             'votes': 47655,
             'pct': 28.21},
            {'n': 5,
             'parties': ['Hrvatska stranka prava - 1861 - HSP - 1861'],
             'holder': 'Dobroslav Paraga',
             'votes': 5072,
             'pct': 3.0},
            {'n': 6,
             'parties': ['Hrvatska stranka umirovljenika - HSU',
                         'Akcija socijaldemokrata Hrvatske - ASH'],
             'holder': 'Rudolf Mažuran',
             'votes': 3747,
             'pct': 2.22},
            {'n': 7,
             'parties': ['Socijaldemokratska partija Hrvatske - SDP',
                         'Hrvatska narodna stranka - HNS'],
             'holder': 'Ivica Račan',
             'votes': 27928,
             'pct': 16.54}],
  'seats': [{'list': 'Hrvatska demokratska zajednica - HDZ',
             'n': 2,
             'elected': [{'name': 'Ivan Penić', 'deputy': 'Ivan Brleković'},
                         {'name': 'Dr. sc. Josip Stepanić', 'deputy': 'Damir Sesvećan'}]},
            {'list': 'Hrvatska seljačka stranka - HSS i Hrvatska socijalno liberalna stranka - '
                     'HSLS',
             'n': 1,
             'elected': [{'name': 'Božidar Pankretić', 'deputy': 'Mirko Dreta'}]}]},
 {'code': '02',
  'name': 'Krapinsko-zagorska županija',
  'registered': 116190,
  'voted': 84139,
  'invalid': 3054,
  'valid_total': 81085,
  'lists': [{'n': 1,
             'parties': ['Hrvatska demokratska zajednica - HDZ'],
             'holder': 'Dr. Franjo Tuđman',
             'votes': 36693,
             'pct': 45.25},
            {'n': 2,
             'parties': ['Hrvatska seljačka stranka - HSS',
                         'Hrvatska socijalno liberalna stranka - HSLS'],
             'holder': 'Josip Pankretić',
             'votes': 23946,
             'pct': 29.53},
            {'n': 3,
             'parties': ['Hrvatska stranka umirovljenika - HSU'],
             'holder': 'Rudolf Mažuran',
             'votes': 2378,
             'pct': 2.93},
            {'n': 4,
             'parties': ['Hrvatski nezavisni demokrati - HND'],
             'holder': 'Josip Manolić',
             'votes': 567,
             'pct': 0.7},
            {'n': 5,
             'parties': ['Socijaldemokratska partija Hrvatske - SDP',
                         'Hrvatska narodna stranka - HNS'],
             'holder': 'Ivica Račan',
             'votes': 10740,
             'pct': 13.25},
            {'n': 6,
             'parties': ['Zagorska demokratska stranka - ZDS'],
             'holder': 'Stanko Belina',
             'votes': 6761,
             'pct': 8.34}],
  'seats': [{'list': 'Hrvatska demokratska zajednica - HDZ',
             'n': 2,
             'elected': [{'name': 'Ivan Valent', 'deputy': 'Josip Vukina'},
                         {'name': 'Dragutin Bračun', 'deputy': 'dr. Josip Perinić'}]},
            {'list': 'Hrvatska seljačka stranka - HSS i Hrvatska socijalno liberalna stranka - '
                     'HSLS',
             'n': 1,
             'elected': [{'name': 'Slavko Koković', 'deputy': 'Željko Lisak'}]}]},
 {'code': '03',
  'name': 'Sisačko-moslavačka županija',
  'registered': 157930,
  'voted': 99596,
  'invalid': 3302,
  'valid_total': 96294,
  'lists': [{'n': 1,
             'parties': ['Hrvatska demokratska zajednica - HDZ'],
             'holder': 'Dr. Franjo Tuđman',
             'votes': 53426,
             'pct': 55.48},
            {'n': 2,
             'parties': ['Hrvatska građansko seljačka stranka - HGSS'],
             'holder': 'Mijo Rebrović',
             'votes': 2104,
             'pct': 2.18},
            {'n': 3,
             'parties': ['Hrvatska kršćanska demokratska unija - HKDU'],
             'holder': 'Dr. sc. Marko Veselica',
             'votes': 2099,
             'pct': 2.18},
            {'n': 4,
             'parties': ['Hrvatska seljačka stranka - HSS',
                         'Hrvatska socijalno liberalna stranka - HSLS'],
             'holder': 'Stjepan Radić',
             'votes': 20211,
             'pct': 20.99},
            {'n': 5,
             'parties': ['Hrvatska stranka umirovljenika - HSU'],
             'holder': 'Stjepan Frei, prof.',
             'votes': 3941,
             'pct': 4.09},
            {'n': 6,
             'parties': ['Socijaldemokratska partija Hrvatske - SDP',
                         'Hrvatska narodna stranka - HNS'],
             'holder': 'Ivica Račan',
             'votes': 14513,
             'pct': 15.07}],
  'seats': [{'list': 'Hrvatska demokratska zajednica - HDZ',
             'n': 2,
             'elected': [{'name': 'Božidar Pugelnik', 'deputy': 'Ivan Šantek'},
                         {'name': 'Velimir Kvesić', 'deputy': 'Marija Krupić'}]},
            {'list': 'Hrvatska seljačka stranka - HSS i Hrvatska socijalno liberalna stranka - '
                     'HSLS',
             'n': 1,
             'elected': [{'name': 'Stjepan Marić', 'deputy': 'Josip Vdović'}]}]},
 {'code': '04',
  'name': 'Karlovačka županija',
  'registered': 127056,
  'voted': 85088,
  'invalid': 2672,
  'valid_total': 82416,
  'lists': [{'n': 1,
             'parties': ['Hrvatska demokratska zajednica - HDZ'],
             'holder': 'Dr. Franjo Tuđman',
             'votes': 45333,
             'pct': 55.01},
            {'n': 2,
             'parties': ['Hrvatska građansko seljačka stranka - HGSS'],
             'holder': 'Stjepan Vujanić - Jamnički',
             'votes': 2634,
             'pct': 3.2},
            {'n': 3,
             'parties': ['Hrvatska narodna stranka - HNS',
                         'Socijaldemokratska partija Hrvatske - SDP'],
             'holder': 'Dr. sc. Savka Dapčević - Kučar',
             'votes': 7782,
             'pct': 9.44},
            {'n': 4,
             'parties': ['Hrvatska socijalno liberalna stranka - HSLS',
                         'Hrvatska seljačka stranka - HSS'],
             'holder': 'Vladimir Gotovac',
             'votes': 19523,
             'pct': 23.69},
            {'n': 5,
             'parties': ['Hrvatska stranka prava - 1861 - HSP - 1861'],
             'holder': 'Dobroslav Paraga',
             'votes': 3234,
             'pct': 3.92},
            {'n': 6,
             'parties': ['Socijalno-demokratska unija Hrvatske - SDU'],
             'holder': 'Vladimir Bebić',
             'votes': 3910,
             'pct': 4.74}],
  'seats': [{'list': 'Hrvatska demokratska zajednica - HDZ',
             'n': 2,
             'elected': [{'name': 'Pavao Miljavac', 'deputy': 'Ivan Novosel'},
                         {'name': 'Vladimir Katić', 'deputy': 'Željko Šančić'}]},
            {'list': 'Hrvatska seljačka stranka - HSS i Hrvatska socijalno liberalna stranka - '
                     'HSLS',
             'n': 1,
             'elected': [{'name': 'Ankica Mamić', 'deputy': 'Ivan Vuković'}]}]},
 {'code': '05',
  'name': 'Varaždinska županija',
  'registered': 151672,
  'voted': 111065,
  'invalid': 3366,
  'valid_total': 107699,
  'lists': [{'n': 1,
             'parties': ['Hrvatska demokratska seljačka stranka - HDSS'],
             'holder': 'Zvonimir Rihtarić',
             'votes': 4549,
             'pct': 4.22},
            {'n': 2,
             'parties': ['Hrvatska demokratska zajednica - HDZ'],
             'holder': 'Dr. Franjo Tuđman',
             'votes': 44521,
             'pct': 41.34},
            {'n': 3,
             'parties': ['Hrvatska kršćanska demokratska unija - HKDU'],
             'holder': 'Mr. sc. Ivan Kovač',
             'votes': 2701,
             'pct': 2.51},
            {'n': 4,
             'parties': ['Hrvatska seljačka stranka - HSS',
                         'Hrvatska socijalno liberalna stranka - HSLS'],
             'holder': 'Dr. sc. Zvonimir Sabati',
             'votes': 30870,
             'pct': 28.66},
            {'n': 5,
             'parties': ['Hrvatska stranka prava - 1861 - HSP - 1861'],
             'holder': 'Dobroslav Paraga',
             'votes': 2702,
             'pct': 2.51},
            {'n': 6,
             'parties': ['Hrvatska stranka umirovljenika - HSU'],
             'holder': 'Dr. sc. Josip Sudec',
             'votes': 4561,
             'pct': 4.23},
            {'n': 7,
             'parties': ['Hrvatski nezavisni demokrati - HND'],
             'holder': 'Josip Manolić',
             'votes': 409,
             'pct': 0.38},
            {'n': 8,
             'parties': ['Nezavisna stranka prava - NSP'],
             'holder': 'Zvonimir Kramarić',
             'votes': 754,
             'pct': 0.7},
            {'n': 9,
             'parties': ['Socijaldemokratska partija Hrvatske - SDP',
                         'Hrvatska narodna stranka - HNS'],
             'holder': 'Ivica Račan',
             'votes': 14990,
             'pct': 13.92},
            {'n': 10,
             'parties': ['Zagorska demokratska stranka - ZDS'],
             'holder': 'Dubravka Margeta Ostojić',
             'votes': 1642,
             'pct': 1.52}],
  'seats': [{'list': 'Hrvatska demokratska zajednica - HDZ',
             'n': 2,
             'elected': [{'name': 'Marijan Mlinarić, dr. med.', 'deputy': 'mr. Franjo Križanić'},
                         {'name': 'Šimun Kujavec, dipl. oec.',
                          'deputy': 'Ratimir Čavlović, dipl. ing.'}]},
            {'list': 'Hrvatska seljačka stranka - HSS i Hrvatska socijalno liberalna stranka - '
                     'HSLS',
             'n': 1,
             'elected': [{'name': 'Dr. sc. Zvonimir Sabati', 'deputy': 'Miroslav Pečevski'}]}]},
 {'code': '06',
  'name': 'Koprivničko-križevačka županija',
  'registered': 103878,
  'voted': 74670,
  'invalid': 1866,
  'valid_total': 72804,
  'lists': [{'n': 1,
             'parties': ['Hrvatska demokratska zajednica - HDZ'],
             'holder': 'Dr. Franjo Tuđman',
             'votes': 33662,
             'pct': 46.24},
            {'n': 2,
             'parties': ['Hrvatska kršćanska demokratska stranka - HKDS'],
             'holder': 'Marijan Ivančan, dipl. iur.',
             'votes': 1265,
             'pct': 1.74},
            {'n': 3,
             'parties': ['Hrvatska seljačka stranka - HSS',
                         'Hrvatska socijalno liberalna stranka - HSLS'],
             'holder': 'Zlatko Tomčić, dipl. ing.',
             'votes': 22365,
             'pct': 30.72},
            {'n': 4,
             'parties': ['Hrvatska stranka prava - 1861 - HSP - 1861'],
             'holder': 'Dobroslav Paraga',
             'votes': 3138,
             'pct': 4.31},
            {'n': 5,
             'parties': ['Socijaldemokratska partija Hrvatske - SDP',
                         'Hrvatska narodna stranka - HNS',
                         'Hrvatska kršćanska demokratska unija - HKDU'],
             'holder': 'Ivica Račan',
             'votes': 12374,
             'pct': 17.0}],
  'seats': [{'list': 'Hrvatska demokratska zajednica - HDZ',
             'n': 2,
             'elected': [{'name': 'Ivan Lacković', 'deputy': 'Zvonimir Majdančić'},
                         {'name': 'Nikola Gregur', 'deputy': 'Ivana Sučec-Trakoštanec'}]},
            {'list': 'Hrvatska seljačka stranka - HSS i Hrvatska socijalno liberalna stranka - '
                     'HSLS',
             'n': 1,
             'elected': [{'name': 'Ivan Stančer', 'deputy': 'Matija Dolenec'}]}]},
 {'code': '07',
  'name': 'Bjelovarsko-bilogorska županija',
  'registered': 112147,
  'voted': 82764,
  'invalid': 2370,
  'valid_total': 80394,
  'lists': [{'n': 1,
             'parties': ['Hrvatska demokratska zajednica - HDZ'],
             'holder': 'Dr. Franjo Tuđman',
             'votes': 38551,
             'pct': 47.95},
            {'n': 2,
             'parties': ['Hrvatska kršćanska demokratska unija - HKDU'],
             'holder': 'Dr. sc. Marko Veselica',
             'votes': 1875,
             'pct': 2.33},
            {'n': 3,
             'parties': ['Hrvatska proljeća - HP'],
             'holder': 'Dr. sc. Goran Dodig',
             'votes': 616,
             'pct': 0.77},
            {'n': 4,
             'parties': ['Hrvatska seljačka stranka - HSS',
                         'Hrvatska socijalno liberalna stranka - HSLS'],
             'holder': 'Željko Ledinski, dipl. ing.',
             'votes': 26984,
             'pct': 33.56},
            {'n': 5,
             'parties': ['Hrvatska stranka prava - 1861 - HSP - 1861'],
             'holder': 'Dobroslav Paraga',
             'votes': 1758,
             'pct': 2.19},
            {'n': 6,
             'parties': ['Nezavisna stranka prava - NSP'],
             'holder': 'Marijan Mihalinec',
             'votes': 395,
             'pct': 0.49},
            {'n': 7,
             'parties': ['Socijaldemokratska partija Hrvatske - SDP',
                         'Hrvatska narodna stranka - HNS'],
             'holder': 'Ivica Račan',
             'votes': 9161,
             'pct': 11.4},
            {'n': 8,
             'parties': ['Stranka Roma Hrvatske - SRH'],
             'holder': 'Stevo Đurđević',
             'votes': 1054,
             'pct': 1.31}],
  'seats': [{'list': 'Hrvatska demokratska zajednica - HDZ',
             'n': 2,
             'elected': [{'name': 'Mile Ćuk', 'deputy': 'Vinko Jelić Balta'},
                         {'name': 'Zvonimir Novoselec', 'deputy': 'Marijan Zadre'}]},
            {'list': 'Hrvatska seljačka stranka - HSS i Hrvatska socijalno liberalna stranka - '
                     'HSLS',
             'n': 1,
             'elected': [{'name': 'Petar Jurušić', 'deputy': 'Milan Šašinović'}]}]},
 {'code': '08',
  'name': 'Primorsko-goranska županija',
  'registered': 264032,
  'voted': 188602,
  'invalid': 4848,
  'valid_total': 183754,
  'lists': [{'n': 1,
             'parties': ['Hrvatska čista stranka prava - HČSP'],
             'holder': 'Ivan Gabelica, dipl. iur.',
             'votes': 3094,
             'pct': 1.68},
            {'n': 2,
             'parties': ['Hrvatska demokratska zajednica - HDZ'],
             'holder': 'Dr. Franjo Tuđman',
             'votes': 56790,
             'pct': 30.91},
            {'n': 3,
             'parties': ['Hrvatska građansko seljačka stranka - HGSS',
                         'Hrvatski nezavisni demokrati - HND'],
             'holder': 'Dr. sc. Vinko Hlača',
             'votes': 3525,
             'pct': 1.92},
            {'n': 4,
             'parties': ['Hrvatska proljeća - HP'],
             'holder': 'Dr. sc. Juraj Plenković',
             'votes': 838,
             'pct': 0.46},
            {'n': 5,
             'parties': ['Hrvatska socijalno liberalna stranka - HSLS',
                         'Hrvatska seljačka stranka - HSS'],
             'holder': 'Vladimir Gotovac',
             'votes': 28333,
             'pct': 15.42},
            {'n': 6,
             'parties': ['Hrvatska stranka prava - 1861 - HSP - 1861'],
             'holder': 'Dobroslav Paraga',
             'votes': 4563,
             'pct': 2.48},
            {'n': 7,
             'parties': ['Hrvatska stranka umirovljenika - HSU'],
             'holder': 'Lucijan Kos',
             'votes': 7276,
             'pct': 3.96},
            {'n': 8,
             'parties': ['Istarski demokratski sabor - IDS'],
             'holder': 'Damir Kajin',
             'votes': 10806,
             'pct': 5.88},
            {'n': 9,
             'parties': ['Socijaldemokratska partija Hrvatske - SDP',
                         'Primorsko goranski savez - PGS',
                         'Hrvatska narodna stranka - HNS'],
             'holder': 'Slavko Linić',
             'votes': 60391,
             'pct': 32.87},
            {'n': 10,
             'parties': ['Socijalno-demokratska unija Hrvatske - SDU',
                         'Stranka demokratske akcije Hrvatske - SDA HRVATSKE'],
             'holder': 'Vladimir Bebić',
             'votes': 5326,
             'pct': 2.9},
            {'n': 11,
             'parties': ['Srpska narodna stranka - SNS'],
             'holder': 'Milan Đukić',
             'votes': 2812,
             'pct': 1.53}],
  'seats': [{'list': 'Socijaldemokratska partija Hrvatske - SDP, Primorsko-goranski savez - PGS i '
                     'Hrvatska narodna stranka - HNS',
             'n': 2,
             'elected': [{'name': 'Zlatko Komadina', 'deputy': 'Vojko Obersnel'},
                         {'name': 'Josip Kukuljan', 'deputy': 'mr. sc. Matko Županić'}]},
            {'list': 'Hrvatska demokratska zajednica - HDZ',
             'n': 1,
             'elected': [{'name': 'Dr. sc. Katica Ivanišević', 'deputy': 'Željko Fučkar'}]}]},
 {'code': '09',
  'name': 'Ličko-senjska županija',
  'registered': 47839,
  'voted': 31529,
  'invalid': 1070,
  'valid_total': 30459,
  'lists': [{'n': 1,
             'parties': ['Hrvatska demokratska zajednica - HDZ'],
             'holder': 'Dr. Franjo Tuđman',
             'votes': 19213,
             'pct': 63.08},
            {'n': 2,
             'parties': ['Hrvatska narodna stranka - HNS',
                         'Socijaldemokratska partija Hrvatske - SDP'],
             'holder': 'Martin Špegelj',
             'votes': 2320,
             'pct': 7.62},
            {'n': 3,
             'parties': ['Hrvatska seljačka stranka - HSS'],
             'holder': 'Mate Čop',
             'votes': 5711,
             'pct': 18.75},
            {'n': 4,
             'parties': ['Hrvatska socijalno liberalna stranka - HSLS'],
             'holder': 'Vladimir Gotovac',
             'votes': 3215,
             'pct': 10.56}],
  'seats': [{'list': 'Hrvatska demokratska zajednica - HDZ',
             'n': 3,
             'elected': [{'name': 'Dražen Bobinac', 'deputy': 'Pavao Račić'},
                         {'name': 'Ante Frković', 'deputy': 'Milan Galić'},
                         {'name': 'Mr. Miroslav Rožić', 'deputy': 'Branko Butković'}]}]},
 {'code': '10',
  'name': 'Virovitičko-podravska županija',
  'registered': 79341,
  'voted': 56422,
  'invalid': 2099,
  'valid_total': 54323,
  'lists': [{'n': 1,
             'parties': ['Hrvatska čista stranka prava - HČSP'],
             'holder': 'Ivan Gabelica, dipl. iur.',
             'votes': 1324,
             'pct': 2.44},
            {'n': 2,
             'parties': ['Hrvatska demokratska zajednica - HDZ'],
             'holder': 'Dr. Franjo Tuđman',
             'votes': 25821,
             'pct': 47.53},
            {'n': 3,
             'parties': ['Hrvatska narodna stranka - HNS',
                         'Socijaldemokratska partija Hrvatske - SDP'],
             'holder': 'Martin Špegelj',
             'votes': 5847,
             'pct': 10.76},
            {'n': 4,
             'parties': ['Hrvatska seljačka stranka - HSS',
                         'Hrvatska socijalno liberalna stranka - HSLS'],
             'holder': 'Josip Pankretić',
             'votes': 18178,
             'pct': 33.46},
            {'n': 5,
             'parties': ['Hrvatska seljačko radnička stranka (Stranka istine i pravde) - HSRS'],
             'holder': 'Josip Dent',
             'votes': 1542,
             'pct': 2.84},
            {'n': 6,
             'parties': ['Hrvatska stranka prava - 1861 - HSP - 1861'],
             'holder': 'Dobroslav Paraga',
             'votes': 1611,
             'pct': 2.97}],
  'seats': [{'list': 'Hrvatska demokratska zajednica - HDZ',
             'n': 2,
             'elected': [{'name': 'Jozo Medved', 'deputy': 'Katica Ciprijanović'},
                         {'name': 'Stjepan Mikolčić', 'deputy': 'Ivan Slamić'}]},
            {'list': 'Hrvatska seljačka stranka - HSS i Hrvatska socijalno liberalna stranka - '
                     'HSLS',
             'n': 1,
             'elected': [{'name': 'Željko Pecek', 'deputy': 'Ivan Bajt'}]}]},
 {'code': '11',
  'name': 'Požeško-slavonska županija',
  'registered': 69343,
  'voted': 50797,
  'invalid': 1130,
  'valid_total': 49667,
  'lists': [{'n': 1,
             'parties': ['Hrvatska demokratska zajednica - HDZ'],
             'holder': 'Dr. Franjo Tuđman',
             'votes': 28295,
             'pct': 56.97},
            {'n': 2,
             'parties': ['Hrvatska kršćanska demokratska unija - HKDU'],
             'holder': 'Mato Nosić, prof.',
             'votes': 3090,
             'pct': 6.22},
            {'n': 3,
             'parties': ['Hrvatska narodna stranka - HNS',
                         'Socijaldemokratska partija Hrvatske - SDP'],
             'holder': 'Stjepan Mesić, dipl. iur.',
             'votes': 5636,
             'pct': 11.35},
            {'n': 4,
             'parties': ['Hrvatska socijalno liberalna stranka - HSLS',
                         'Hrvatska seljačka stranka - HSS'],
             'holder': 'Vladimir Gotovac',
             'votes': 12646,
             'pct': 25.46}],
  'seats': [{'list': 'Hrvatska demokratska zajednica - HDZ',
             'n': 2,
             'elected': [{'name': 'Mario Včelik', 'deputy': 'Mato Novačić'},
                         {'name': 'Anto Bagarić', 'deputy': 'Ivan Marijanović'}]},
            {'list': 'Hrvatska seljačka stranka - HSS i Hrvatska socijalno liberalna stranka - '
                     'HSLS',
             'n': 1,
             'elected': [{'name': 'Milan Markanjević', 'deputy': 'Dragan Marin'}]}]},
 {'code': '12',
  'name': 'Brodsko-posavska županija',
  'registered': 139047,
  'voted': 94943,
  'invalid': 2727,
  'valid_total': 92216,
  'lists': [{'n': 1,
             'parties': ['Hrvatska demokratska zajednica - HDZ'],
             'holder': 'Dr. Franjo Tuđman',
             'votes': 51079,
             'pct': 55.39},
            {'n': 2,
             'parties': ['Hrvatska seljačka stranka - HSS',
                         'Hrvatska socijalno liberalna stranka - HSLS'],
             'holder': 'Zlatko Tomčić, dipl. ing.',
             'votes': 16902,
             'pct': 18.33},
            {'n': 3,
             'parties': ['Kršćansko-slavonska koalicija: Hrvatska kršćanska demokratska unija - '
                         'HKDU',
                         'Slavonsko-baranjska hrvatska stranka - SBHS'],
             'holder': 'Dr. sc. Marko Veselica',
             'votes': 4287,
             'pct': 4.65},
            {'n': 4,
             'parties': ['Nezavisna županijska lista'],
             'holder': 'Dr. sc. Anto Matković',
             'votes': 3300,
             'pct': 3.58},
            {'n': 5,
             'parties': ['Socijaldemokratska partija Hrvatske - SDP',
                         'Hrvatska narodna stranka - HNS'],
             'holder': 'Dr. sc. Zdravko Tomac',
             'votes': 16648,
             'pct': 18.05}],
  'seats': [{'list': 'Hrvatska demokratska zajednica - HDZ',
             'n': 3,
             'elected': [{'name': 'Marinko Liović', 'deputy': 'Marko Maričević'},
                         {'name': 'Mirko Tomac', 'deputy': 'Petar Katalinić'},
                         {'name': 'Miroslav Prpić', 'deputy': 'Drago Prgomet'}]}]},
 {'code': '13',
  'name': 'Zadarska županija',
  'registered': 127324,
  'voted': 83377,
  'invalid': 2564,
  'valid_total': 80813,
  'lists': [{'n': 1,
             'parties': ['Hrvatska demokratska zajednica - HDZ'],
             'holder': 'Dr. Franjo Tuđman',
             'votes': 43890,
             'pct': 54.31},
            {'n': 2,
             'parties': ['Hrvatska proljeća - HP'],
             'holder': 'Dr. sc. Goran Dodig',
             'votes': 719,
             'pct': 0.89},
            {'n': 3,
             'parties': ['Hrvatska republikanska zajednica - HRZ'],
             'holder': 'Vice Profaca, prof.',
             'votes': 2347,
             'pct': 2.9},
            {'n': 4,
             'parties': ['Hrvatska socijalno liberalna stranka - HSLS',
                         'Hrvatska seljačka stranka - HSS'],
             'holder': 'Vladimir Gotovac',
             'votes': 17699,
             'pct': 21.9},
            {'n': 5,
             'parties': ['Hrvatska stranka prava - 1861 - HSP - 1861'],
             'holder': 'Dobroslav Paraga',
             'votes': 2497,
             'pct': 3.09},
            {'n': 6,
             'parties': ['Hrvatski nezavisni demokrati - HND'],
             'holder': 'Josip Manolić',
             'votes': 519,
             'pct': 0.64},
            {'n': 7,
             'parties': ['Socijaldemokratska partija Hrvatske - SDP',
                         'Hrvatska narodna stranka - HNS'],
             'holder': 'Ivica Račan',
             'votes': 13142,
             'pct': 16.26}],
  'seats': [{'list': 'Hrvatska demokratska zajednica - HDZ',
             'n': 2,
             'elected': [{'name': 'Šime Prtenjača', 'deputy': 'Julije Derossi'},
                         {'name': 'Živko Kolega', 'deputy': 'Svemir Vrsaljko'}]},
            {'list': 'Hrvatska seljačka stranka - HSS i Hrvatska socijalno liberalna stranka - '
                     'HSLS',
             'n': 1,
             'elected': [{'name': 'Dr. Tereza Ganza-Aras', 'deputy': 'Ivica Kamber'}]}]},
 {'code': '14',
  'name': 'Osječko-baranjska županija',
  'registered': 278851,
  'voted': 222719,
  'invalid': 6731,
  'valid_total': 215988,
  'lists': [{'n': 1,
             'parties': ['Hrvatska demokratska zajednica - HDZ'],
             'holder': 'Dr. Franjo Tuđman',
             'votes': 102116,
             'pct': 47.28},
            {'n': 2,
             'parties': ['Hrvatska kršćanska demokratska unija - HKDU'],
             'holder': 'Dr. sc. Marko Veselica',
             'votes': 3353,
             'pct': 1.55},
            {'n': 3,
             'parties': ['Hrvatska republikanska zajednica - HRZ'],
             'holder': 'Mario Marcos Ostojić',
             'votes': 820,
             'pct': 0.38},
            {'n': 4,
             'parties': ['Hrvatska socijalno liberalna stranka - HSLS',
                         'Hrvatska seljačka stranka - HSS'],
             'holder': 'Vladimir Gotovac',
             'votes': 43922,
             'pct': 20.34},
            {'n': 5,
             'parties': ['Hrvatska stranka prava - HSP'],
             'holder': 'Anto Đapić, dipl. iur.',
             'votes': 13003,
             'pct': 6.02},
            {'n': 6,
             'parties': ['Nezavisna županijska lista'],
             'holder': 'Tomislav Merčep, ing.',
             'votes': 2866,
             'pct': 1.33},
            {'n': 7,
             'parties': ['Slavonsko-baranjska hrvatska stranka - SBHS'],
             'holder': 'Slavko Vukšić',
             'votes': 5326,
             'pct': 2.47},
            {'n': 8,
             'parties': ['Socijaldemokratska partija Hrvatske - SDP',
                         'Hrvatska narodna stranka - HNS'],
             'holder': 'Ivica Račan',
             'votes': 15286,
             'pct': 7.08},
            {'n': 9,
             'parties': ['Socijalno-demokratska unija Hrvatske - SDU'],
             'holder': 'Vladimir Bebić',
             'votes': 3919,
             'pct': 1.81},
            {'n': 10,
             'parties': ['Srpska narodna stranka - SNS'],
             'holder': 'Milan Đukić',
             'votes': 25377,
             'pct': 11.75}],
  'seats': [{'list': 'Hrvatska demokratska zajednica - HDZ',
             'n': 2,
             'elected': [{'name': 'Branimir Glavaš', 'deputy': 'Mato Šimić'},
                         {'name': 'Josip Majdenić', 'deputy': 'Marko Bagarić'}]},
            {'list': 'Hrvatska seljačka stranka - HSS i Hrvatska socijalno liberalna stranka - '
                     'HSLS',
             'n': 1,
             'elected': [{'name': 'Dr. sc. Vilim Herman', 'deputy': 'Željko Režić'}]}]},
 {'code': '15',
  'name': 'Šibensko-kninska županija',
  'registered': 87099,
  'voted': 59175,
  'invalid': 1869,
  'valid_total': 57306,
  'lists': [{'n': 1,
             'parties': ['Hrvatska čista stranka prava - HČSP'],
             'holder': 'Ivan Gabelica, dipl. iur.',
             'votes': 1603,
             'pct': 2.8},
            {'n': 2,
             'parties': ['Hrvatska demokratska zajednica - HDZ'],
             'holder': 'Dr. Franjo Tuđman',
             'votes': 27683,
             'pct': 48.31},
            {'n': 3,
             'parties': ['Hrvatska kršćanska demokratska stranka - HKDS'],
             'holder': 'Nenad Bubrić, ing.',
             'votes': 1086,
             'pct': 1.9},
            {'n': 4,
             'parties': ['Hrvatska proljeća - HP'],
             'holder': 'Ivan Bačić',
             'votes': 458,
             'pct': 0.8},
            {'n': 5,
             'parties': ['Hrvatska republikanska zajednica - HRZ'],
             'holder': 'Mario Marcos Ostojić',
             'votes': 819,
             'pct': 1.43},
            {'n': 6,
             'parties': ['Hrvatska seljačka stranka - HSS'],
             'holder': 'Krunoslav Mazalin',
             'votes': 5550,
             'pct': 9.68},
            {'n': 7,
             'parties': ['Hrvatska socijalno liberalna stranka - HSLS'],
             'holder': 'Vladimir Gotovac',
             'votes': 6083,
             'pct': 10.61},
            {'n': 8,
             'parties': ['Hrvatski dalmatinski dom - HDD'],
             'holder': 'Stjepan Lozo, prof.',
             'votes': 728,
             'pct': 1.27},
            {'n': 9,
             'parties': ['Nezavisna županijska lista'],
             'holder': 'Vice Vukov',
             'votes': 2434,
             'pct': 4.25},
            {'n': 10,
             'parties': ['Nezavisna županijska lista'],
             'holder': 'Davor Živković',
             'votes': 752,
             'pct': 1.31},
            {'n': 11,
             'parties': ['Socijaldemokratska partija Hrvatske - SDP',
                         'Hrvatska narodna stranka - HNS'],
             'holder': 'Ivica Račan',
             'votes': 10110,
             'pct': 17.64}],
  'seats': [{'list': 'Hrvatska demokratska zajednica - HDZ',
             'n': 2,
             'elected': [{'name': 'Mr. sc. Paško Bubalo', 'deputy': 'Jure Zečević'},
                         {'name': 'Ante Dželalija', 'deputy': 'Marinko Čavka'}]},
            {'list': 'Socijaldemokratska partija Hrvatske - SDP i Hrvatska narodna stranka - HNS',
             'n': 1,
             'elected': [{'name': 'Ivan Ninić, dipl. iur.', 'deputy': 'Branko Sruk, dr. med.'}]}]},
 {'code': '16',
  'name': 'Vukovarsko-srijemska županija',
  'registered': 164748,
  'voted': 136897,
  'invalid': 15506,
  'valid_total': 121391,
  'lists': [{'n': 1,
             'parties': ['Hrvatska čista stranka prava - HČSP'],
             'holder': 'Ivan Gabelica, dipl. iur.',
             'votes': 2374,
             'pct': 1.96},
            {'n': 2,
             'parties': ['Hrvatska demokratska zajednica - HDZ'],
             'holder': 'Dr. Franjo Tuđman',
             'votes': 65149,
             'pct': 53.67},
            {'n': 3,
             'parties': ['Hrvatska kršćanska demokratska unija - HKDU'],
             'holder': 'Anto Lovrić',
             'votes': 2040,
             'pct': 1.68},
            {'n': 4,
             'parties': ['Hrvatska narodna stranka - HNS',
                         'Socijaldemokratska partija Hrvatske - SDP'],
             'holder': 'Stjepan Mesić, dipl. iur.',
             'votes': 6488,
             'pct': 5.34},
            {'n': 5,
             'parties': ['Hrvatska socijalno liberalna stranka - HSLS',
                         'Hrvatska seljačka stranka - HSS'],
             'holder': 'Vladimir Gotovac',
             'votes': 18024,
             'pct': 14.85},
            {'n': 6,
             'parties': ['Hrvatska stranka prava - 1861 - HSP - 1861'],
             'holder': 'Dobroslav Paraga',
             'votes': 3499,
             'pct': 2.88},
            {'n': 7,
             'parties': ['Slavonsko-baranjska hrvatska stranka - SBHS'],
             'holder': 'Mirko Hunjadi, prof.',
             'votes': 2999,
             'pct': 2.47},
            {'n': 8,
             'parties': ['Socijalno-demokratska unija Hrvatske - SDU'],
             'holder': 'Vladimir Bebić',
             'votes': 20818,
             'pct': 17.15}],
  'seats': [{'list': 'Hrvatska demokratska zajednica - HDZ',
             'n': 3,
             'elected': [{'name': 'Vlado Ošust, dipl. oec.', 'deputy': 'Petar Mlinarić'},
                         {'name': 'Dragan Papac, dipl. ing.',
                          'deputy': 'Andrija Matić, dipl. ing.'},
                         {'name': 'Rudolf König, ing.',
                          'deputy': 'Petar Čobanković, dipl. ing.'}]}]},
 {'code': '17',
  'name': 'Splitsko-dalmatinska županija',
  'registered': 362430,
  'voted': 257325,
  'invalid': 6936,
  'valid_total': 250389,
  'lists': [{'n': 1,
             'parties': ['Akcija socijaldemokrata Hrvatske - ASH',
                         'Hrvatska stranka umirovljenika - HSU'],
             'holder': 'Stipe Ljubičić',
             'votes': 10565,
             'pct': 4.22},
            {'n': 2,
             'parties': ['Dalmatinska akcija - DA', 'Socijalno-demokratska unija Hrvatske - SDU'],
             'holder': 'Vladimir Bebić',
             'votes': 5259,
             'pct': 2.1},
            {'n': 3,
             'parties': ['Hrvatska čista stranka prava - HČSP'],
             'holder': 'Luka Podrug',
             'votes': 10297,
             'pct': 4.11},
            {'n': 4,
             'parties': ['Hrvatska demokratska zajednica - HDZ'],
             'holder': 'Dr. Franjo Tuđman',
             'votes': 101109,
             'pct': 40.38},
            {'n': 5,
             'parties': ['Hrvatska kršćanska demokratska unija - HKDU'],
             'holder': 'Dr. sc. Marko Veselica',
             'votes': 7275,
             'pct': 2.91},
            {'n': 6,
             'parties': ['Hrvatska proljeća - HP'],
             'holder': 'Dr. sc. Goran Dodig',
             'votes': 5581,
             'pct': 2.23},
            {'n': 7,
             'parties': ['Hrvatska socijalno liberalna stranka - HSLS',
                         'Hrvatska seljačka stranka - HSS',
                         'Hrvatska narodna stranka - HNS'],
             'holder': 'Vladimir Gotovac',
             'votes': 60574,
             'pct': 24.19},
            {'n': 8,
             'parties': ['Hrvatska stranka - HS'],
             'holder': 'Frano Čačija',
             'votes': 545,
             'pct': 0.22},
            {'n': 9,
             'parties': ['Hrvatska stranka prava - 1861 - HSP - 1861'],
             'holder': 'Dobroslav Paraga',
             'votes': 4411,
             'pct': 1.76},
            {'n': 10,
             'parties': ['Hrvatski dalmatinski dom - HDD'],
             'holder': 'Stjepan Lozo, prof.',
             'votes': 3946,
             'pct': 1.58},
            {'n': 11,
             'parties': ['Socijaldemokratska partija Hrvatska - SDP'],
             'holder': 'Ivica Račan',
             'votes': 40827,
             'pct': 16.31}],
  'seats': [{'list': 'Hrvatska demokratska zajednica - HDZ',
             'n': 2,
             'elected': [{'name': 'Ante Dolić', 'deputy': 'Kruno Peronja'},
                         {'name': 'Zvonimir Puljić', 'deputy': 'Jure Bitunjac'}]},
            {'list': 'Hrvatska socijalno liberalna stranka - HSLS, Hrvatska seljačka stranka - HSS '
                     'i Hrvatska narodna stranka - HNS',
             'n': 1,
             'elected': [{'name': 'Ivan Škarić', 'deputy': 'Joško Kontić'}]}]},
 {'code': '18',
  'name': 'Istarska županija',
  'registered': 173670,
  'voted': 126051,
  'invalid': 3605,
  'valid_total': 122446,
  'lists': [{'n': 1,
             'parties': ['Akcija socijaldemokrata Hrvatske - ASH'],
             'holder': 'Ratko Crnobori',
             'votes': 1310,
             'pct': 1.07},
            {'n': 2,
             'parties': ['Hrvatska demokratska zajednica - HDZ'],
             'holder': 'Dr. Franjo Tuđman',
             'votes': 19661,
             'pct': 16.06},
            {'n': 3,
             'parties': ['Hrvatska socijalno liberalna stranka - HSLS',
                         'Hrvatska seljačka stranka - HSS'],
             'holder': 'Vladimir Gotovac',
             'votes': 11272,
             'pct': 9.21},
            {'n': 4,
             'parties': ['Hrvatska stranka zelenih - HSZ'],
             'holder': 'Mr. Josip - Anton Rupnik',
             'votes': 1837,
             'pct': 1.5},
            {'n': 5,
             'parties': ['Istarska nezavisna stranka - INS'],
             'holder': 'Ante Mihovilović, dr. med.',
             'votes': 2472,
             'pct': 2.02},
            {'n': 6,
             'parties': ['Istarska stranka'],
             'holder': 'Miro Božac',
             'votes': 2092,
             'pct': 1.71},
            {'n': 7,
             'parties': ['Istarski demokratski forum - Foro democratico Istriano - IDF - FDI'],
             'holder': 'Mr. Luciano Delbianco',
             'votes': 14202,
             'pct': 11.6},
            {'n': 8,
             'parties': ['Istarski demokratski sabor - IDS'],
             'holder': 'Damir Kajin',
             'votes': 54077,
             'pct': 44.16},
            {'n': 9,
             'parties': ['Socijaldemokratska partija Hrvatske - SDP',
                         'Hrvatska narodna stranka - HNS'],
             'holder': 'Ivica Račan',
             'votes': 13576,
             'pct': 11.09},
            {'n': 10,
             'parties': ['Socijalno-demokratska unija Hrvatske - SDU'],
             'holder': 'Dr. sc. Branko Horvat',
             'votes': 1947,
             'pct': 1.59}],
  'seats': [{'list': 'Istarski demokratski sabor - IDS',
             'n': 2,
             'elected': [{'name': 'Valter Drandić', 'deputy': 'Aldo Skira'},
                         {'name': 'Emil Soldatić', 'deputy': 'Lido Sošić'}]},
            {'list': 'Hrvatska demokratska zajednica - HDZ',
             'n': 1,
             'elected': [{'name': 'Branko Močibob', 'deputy': 'Mario Glavaš'}]}]},
 {'code': '19',
  'name': 'Dubrovačko-neretvanska županija',
  'registered': 101853,
  'voted': 72698,
  'invalid': 2446,
  'valid_total': 70252,
  'lists': [{'n': 1,
             'parties': ['Dalmatinska akcija - DA', 'Socijalno-demokratska unija Hrvatske - SDU'],
             'holder': 'Dr. sc. Mira Ljubić - Lorger',
             'votes': 3735,
             'pct': 5.32},
            {'n': 2,
             'parties': ['Hrvatska čista stranka prava - HČSP'],
             'holder': 'Ivan Gabelica, dipl. iur.',
             'votes': 864,
             'pct': 1.23},
            {'n': 3,
             'parties': ['Hrvatska demokratska zajednica - HDZ'],
             'holder': 'Dr. Franjo Tuđman',
             'votes': 31102,
             'pct': 44.27},
            {'n': 4,
             'parties': ['Hrvatska kršćanska demokratska unija - HKDU'],
             'holder': 'Dr. sc. Marko Veselica',
             'votes': 3839,
             'pct': 5.46},
            {'n': 5,
             'parties': ['Hrvatska narodna stranka - HNS'],
             'holder': 'Stijepo Martinović',
             'votes': 1335,
             'pct': 1.9},
            {'n': 6,
             'parties': ['Hrvatska seljačka stranka - HSS'],
             'holder': 'Vido Bogdanović, dipl. ing.',
             'votes': 16639,
             'pct': 23.68},
            {'n': 7,
             'parties': ['Hrvatska socijalno liberalna stranka - HSLS'],
             'holder': 'Vladimir Gotovac',
             'votes': 11063,
             'pct': 15.75},
            {'n': 8,
             'parties': ['Hrvatska stranka prava - 1861 - HSP - 1861'],
             'holder': 'Dobroslav Paraga',
             'votes': 1675,
             'pct': 2.38}],
  'seats': [{'list': 'Hrvatska demokratska zajednica - HDZ',
             'n': 2,
             'elected': [{'name': 'Jure Burić', 'deputy': 'Luka Šiljeg'},
                         {'name': 'Niko Bulić', 'deputy': 'dr. Petar Đukan'}]},
            {'list': 'Hrvatska seljačka stranka - HSS',
             'n': 1,
             'elected': [{'name': 'Vido Bogdanović, dipl. ing.', 'deputy': 'Srećko Kljunak'}]}]},
 {'code': '20',
  'name': 'Međimurska županija',
  'registered': 94290,
  'voted': 68902,
  'invalid': 2850,
  'valid_total': 66052,
  'lists': [{'n': 1,
             'parties': ['Hrvatska čista stranka prava - HČSP'],
             'holder': 'Ivan Gabelica, dipl. iur.',
             'votes': 760,
             'pct': 1.15},
            {'n': 2,
             'parties': ['Hrvatska demokratska seljačka stranka - HDSS'],
             'holder': 'Ivan Martan',
             'votes': 1925,
             'pct': 2.91},
            {'n': 3,
             'parties': ['Hrvatska demokratska zajednica - HDZ',
                         'Hrvatska kršćanska demokratska unija - HKDU',
                         'Hrvatska stranka prava - HSP',
                         'Kršćanski demokrati Međimurja - KDM'],
             'holder': 'Dr. Franjo Tuđman',
             'votes': 19534,
             'pct': 29.57},
            {'n': 4,
             'parties': ['Hrvatska građansko seljačka stranka - HGSS'],
             'holder': 'Ivan Korunek',
             'votes': 1650,
             'pct': 2.5},
            {'n': 5,
             'parties': ['Hrvatska narodna stranka - HNS'],
             'holder': 'Dragutin Lesar',
             'votes': 9309,
             'pct': 14.09},
            {'n': 6,
             'parties': ['Hrvatska seljačka stranka - HSS'],
             'holder': 'Zlatko Tomčić, dipl. ing.',
             'votes': 10070,
             'pct': 15.25},
            {'n': 7,
             'parties': ['Hrvatska socijalno liberalna stranka - HSLS'],
             'holder': 'Vladimir Gotovac',
             'votes': 11001,
             'pct': 16.66},
            {'n': 8,
             'parties': ['Hrvatska stranka prava - 1861 - HSP - 1861'],
             'holder': 'Dobroslav Paraga',
             'votes': 1386,
             'pct': 2.1},
            {'n': 9,
             'parties': ['Nezavisna županijska lista'],
             'holder': 'Stjepan Hutinec',
             'votes': 757,
             'pct': 1.15},
            {'n': 10,
             'parties': ['Socijaldemokratska partija Hrvatske - SDP'],
             'holder': 'Ivica Račan',
             'votes': 9660,
             'pct': 14.62}],
  'seats': [{'list': 'Hrvatska demokratska zajednica - HDZ, Hrvatska kršćanska demokratska unija - '
                     'HKDU, Hrvatska stranka prava - HSP i Kršćanski demokrati Međimurja - KDM',
             'n': 1,
             'elected': [{'name': 'Marijan Ramušćak', 'deputy': 'Vladimir Mesarić'}]},
            {'list': 'Hrvatska socijalno liberalna stranka - HSLS',
             'n': 1,
             'elected': [{'name': 'Žarko Katić, dipl. iur.', 'deputy': 'Franjo Makovec'}]},
            {'list': 'Hrvatska seljačka stranka - HSS',
             'n': 1,
             'elected': [{'name': 'Petar Novački, prof.', 'deputy': 'Božidar Kolarić'}]}]},
 {'code': '21',
  'name': 'Grad Zagreb',
  'registered': 671548,
  'voted': 455120,
  'invalid': 10357,
  'valid_total': 444763,
  'lists': [{'n': 1,
             'parties': ['Akcija socijaldemokrata Hrvatske - ASH',
                         'Hrvatska stranka umirovljenika - HSU'],
             'holder': 'Silvije Degen',
             'votes': 25361,
             'pct': 5.7},
            {'n': 2,
             'parties': ['Domovinska građanska stranka - DGS'],
             'holder': 'Drago Mintas',
             'votes': 818,
             'pct': 0.18},
            {'n': 3,
             'parties': ['Hrvatska čista stranka prava - HČSP'],
             'holder': 'Ivan Gabelica, dipl. iur.',
             'votes': 4242,
             'pct': 0.95},
            {'n': 4,
             'parties': ['Hrvatska demokratska stranka prava - HDSP'],
             'holder': 'Krešimir Pavelić, dipl. iur.',
             'votes': 2402,
             'pct': 0.54},
            {'n': 5,
             'parties': ['Hrvatska demokratska zajednica - HDZ'],
             'holder': 'Dr. Franjo Tuđman',
             'votes': 158797,
             'pct': 35.7},
            {'n': 6,
             'parties': ['Hrvatska građansko seljačka stranka - HGSS'],
             'holder': 'Dr. sc. Vladimir Sertić',
             'votes': 3015,
             'pct': 0.68},
            {'n': 7,
             'parties': ['Hrvatska kršćanska demokratska stranka - HKDS'],
             'holder': 'Ivan Keglević, dipl. ing.',
             'votes': 2257,
             'pct': 0.51},
            {'n': 8,
             'parties': ['Hrvatska kršćanska demokratska unija - HKDU'],
             'holder': 'Dr. sc. Marko Veselica',
             'votes': 7259,
             'pct': 1.63},
            {'n': 9,
             'parties': ['Hrvatska proljeća - HP'],
             'holder': 'Dr. sc. Goran Dodig',
             'votes': 1471,
             'pct': 0.33},
            {'n': 10,
             'parties': ['Hrvatska republikanska zajednica - HRZ'],
             'holder': 'Mario Marcos Ostojić',
             'votes': 1328,
             'pct': 0.3},
            {'n': 11,
             'parties': ['Hrvatska seljačka stranka - HSS'],
             'holder': 'Stjepan Radić, prof.',
             'votes': 38414,
             'pct': 8.64},
            {'n': 12,
             'parties': ['Hrvatska socijalno liberalna stranka - HSLS'],
             'holder': 'Vladimir Gotovac',
             'votes': 55971,
             'pct': 12.58},
            {'n': 13,
             'parties': ['Hrvatska stranka - HS'],
             'holder': 'Dr. sc. Vlatko Mićković',
             'votes': 451,
             'pct': 0.1},
            {'n': 14,
             'parties': ['Hrvatska stranka prava - 1861 - HSP - 1861'],
             'holder': 'Dobroslav Paraga',
             'votes': 10616,
             'pct': 2.39},
            {'n': 15,
             'parties': ['Hrvatska stranka zelenih - HSZ'],
             'holder': 'Zlatko Sviben, dipl. ing.',
             'votes': 5971,
             'pct': 1.34},
            {'n': 16,
             'parties': ['Hrvatski nezavisni demokrati - HND'],
             'holder': 'Josip Manolić',
             'votes': 1425,
             'pct': 0.32},
            {'n': 17,
             'parties': ['Hrvatski oslobodilački pokret - HOP'],
             'holder': 'Dr. sc. Srećko Pšeničnik',
             'votes': 2370,
             'pct': 0.53},
            {'n': 18,
             'parties': ['Nezavisna županijska lista'],
             'holder': 'Anđelko Gluić',
             'votes': 1085,
             'pct': 0.24},
            {'n': 19,
             'parties': ['Socijaldemokratska partija Hrvatske - SDP',
                         'Hrvatska narodna stranka - HNS'],
             'holder': 'Ivica Račan',
             'votes': 107329,
             'pct': 24.13},
            {'n': 20,
             'parties': ['Socijalno-demokratska unija Hrvatske - SDU'],
             'holder': 'Dr. sc. Branko Horvat',
             'votes': 2914,
             'pct': 0.66},
            {'n': 21,
             'parties': ['Srpska narodna stranka - SNS'],
             'holder': 'Milan Đukić',
             'votes': 4180,
             'pct': 0.94},
            {'n': 22,
             'parties': ['Zagorska demokratska stranka - ZDS'],
             'holder': 'Marko Medar',
             'votes': 7087,
             'pct': 1.59}],
  'seats': [{'list': 'Hrvatska demokratska zajednica - HDZ',
             'n': 2,
             'elected': [{'name': 'Zvonimir Červenko', 'deputy': 'mr. sc. Božo Biškupić'},
                         {'name': 'Dr. sc. Ivica Kostović', 'deputy': 'Stjepan Brolich'}]},
            {'list': 'Socijaldemokratska partija Hrvatske - SDP i Hrvatska narodna stranka - HNS',
             'n': 1,
             'elected': [{'name': 'Ratko Maričić', 'deputy': 'Željka Antunović'}]}]}]
