# Generated by Django 6.0.3 on 2026-03-19 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'counties',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'parties',
            },
        ),
        migrations.CreateModel(
            name='ElectionRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='elections.election')),
            ],
            options={
                'unique_together': {('election', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='ElectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtypes', to='elections.electiontype')),
            ],
        ),
        migrations.AddField(
            model_name='election',
            name='election_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elections', to='elections.electiontype'),
        ),
        migrations.CreateModel(
            name='ElectoralDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='elections.election')),
            ],
            options={
                'unique_together': {('election', 'number')},
            },
        ),
        migrations.CreateModel(
            name='ElectoralList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electoral_lists', to='elections.electoraldistrict')),
                ('election_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electoral_lists', to='elections.electionround')),
                ('parties', models.ManyToManyField(blank=True, related_name='electoral_lists', to='elections.party')),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('grad', 'Grad'), ('općina', 'Općina'), ('država', 'Država')], max_length=20)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='elections.county')),
            ],
            options={
                'verbose_name_plural': 'municipalities',
                'ordering': ['county', 'name'],
                'unique_together': {('county', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(db_index=True, max_length=400)),
            ],
            options={
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='elections_p_last_na_01de4d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Candidacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_on_list', models.IntegerField()),
                ('electoral_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidacies', to='elections.electorallist')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidacies', to='elections.person')),
            ],
            options={
                'verbose_name_plural': 'candidacies',
            },
        ),
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=300)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polling_stations', to='elections.municipality')),
            ],
            options={
                'ordering': ['municipality', 'number'],
            },
        ),
        migrations.CreateModel(
            name='ListResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('electoral_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='elections.electorallist')),
                ('polling_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_results', to='elections.pollingstation')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('candidacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='elections.candidacy')),
                ('polling_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_results', to='elections.pollingstation')),
            ],
        ),
        migrations.CreateModel(
            name='TurnoutData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_voters', models.IntegerField(default=0)),
                ('ballots_cast', models.IntegerField(default=0)),
                ('valid_ballots', models.IntegerField(default=0)),
                ('invalid_ballots', models.IntegerField(default=0)),
                ('election_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnout_data', to='elections.electionround')),
                ('polling_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnout_data', to='elections.pollingstation')),
            ],
            options={
                'verbose_name_plural': 'turnout data',
            },
        ),
        migrations.AlterUniqueTogether(
            name='election',
            unique_together={('election_type', 'year', 'name')},
        ),
        migrations.AddIndex(
            model_name='electorallist',
            index=models.Index(fields=['election_round', 'district'], name='elections_e_electio_fdaf55_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidacy',
            unique_together={('electoral_list', 'position_on_list')},
        ),
        migrations.AlterUniqueTogether(
            name='pollingstation',
            unique_together={('municipality', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='listresult',
            unique_together={('electoral_list', 'polling_station')},
        ),
        migrations.AlterUniqueTogether(
            name='candidateresult',
            unique_together={('candidacy', 'polling_station')},
        ),
        migrations.AlterUniqueTogether(
            name='turnoutdata',
            unique_together={('election_round', 'polling_station')},
        ),
    ]
