# Generated by Django 6.0.3 on 2026-05-26 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectedMandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=120)),
                ('candidacy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='elected_mandate', to='elections.candidacy')),
            ],
        ),
    ]
