# Generated by Django 6.0.3 on 2026-07-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_electedmandate'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionround',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
