# Generated by Django 6.0.3 on 2026-09-10 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_electionround_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParliamentMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(blank=True, max_length=200)),
                ('minority', models.BooleanField(default=False, help_text='Elected in district XII (nacionalne manjine)')),
                ('note', models.CharField(blank=True, help_text='Mandate start/end, reactivation after mirovanje, etc.', max_length=300)),
                ('candidacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parliament_members', to='elections.candidacy')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parliament_members', to='elections.election')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parliament_memberships', to='elections.person')),
            ],
            options={
                'ordering': ['person__last_name', 'person__first_name'],
                'indexes': [models.Index(fields=['election'], name='elections_p_electio_bcdcab_idx')],
                'unique_together': {('election', 'person')},
            },
        ),
    ]
