# Generated by Django 6.0.3 on 2026-09-12 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_parliamentmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='parliamentmember',
            name='district',
            field=models.ForeignKey(blank=True, help_text='Electoral district the member was elected in, where the published roster says. Null when it does not.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parliament_members', to='elections.electoraldistrict'),
        ),
    ]
